/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package regextester;

import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erik Norvelle <erik.norvelle@cyberlogos.co>
 */
public class MainWindow extends javax.swing.JFrame {
    
    private RegexTester application;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(RegexTester application) {
        initComponents();
        this.application = application;
        String oldRegex = this.application.getProps().getProperty("regex");
        if (oldRegex != null)
            this.jRegexField.setText(oldRegex);
        String oldText = this.application.getProps().getProperty("text");
        if (oldText != null)
            this.jTestTextArea.setText(oldText);
    }

    /**
     * A single-access point for reporting exceptions to the user.
     * 
     * @param message
     */
    public void reportException(String message) {
        JOptionPane.showMessageDialog(this,
            Utils.wordWrapString(message, 50),
            "Program error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRegexField = new javax.swing.JTextField();
        jTestButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDoesMatchLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTestTextArea = new javax.swing.JTextArea();
        jMultilineCheckbox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCaseInsensitiveCheckbox = new javax.swing.JCheckBox();
        jDotallCheckbox = new javax.swing.JCheckBox();
        jLiteralCheckbox = new javax.swing.JCheckBox();
        jCharacterClassesCheckbox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jResultsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        jLabel1.setText("Regex:");

        jTestButton.setText("Run Test");
        jTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Test text:");

        jLabel3.setText("Matches:");

        jDoesMatchLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jDoesMatchLabel.setText("N/A");

        jTestTextArea.setColumns(20);
        jTestTextArea.setRows(5);
        jScrollPane3.setViewportView(jTestTextArea);

        jMultilineCheckbox.setText("Multiline");

        jLabel4.setText("Flags:");

        jCaseInsensitiveCheckbox.setText("Case insensitive");

        jDotallCheckbox.setText("Dot matches newline");

        jLiteralCheckbox.setText("Literal");

        jCharacterClassesCheckbox.setText("Character classes");

        jResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Match 1", "Match 2", "Match 3", "Match 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jResultsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRegexField)
                        .addGap(18, 18, 18)
                        .addComponent(jTestButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jMultilineCheckbox)
                                .addGap(18, 18, 18)
                                .addComponent(jCaseInsensitiveCheckbox)
                                .addGap(18, 18, 18)
                                .addComponent(jDotallCheckbox)
                                .addGap(18, 18, 18)
                                .addComponent(jLiteralCheckbox)
                                .addGap(18, 18, 18)
                                .addComponent(jCharacterClassesCheckbox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDoesMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRegexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTestButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMultilineCheckbox)
                    .addComponent(jLabel4)
                    .addComponent(jCaseInsensitiveCheckbox)
                    .addComponent(jDotallCheckbox)
                    .addComponent(jLiteralCheckbox)
                    .addComponent(jCharacterClassesCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDoesMatchLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestButtonActionPerformed
        Pattern pattern;
        try {
            int flags = 0;
            if (this.jMultilineCheckbox.isSelected()) flags = Pattern.MULTILINE;
            if (this.jCaseInsensitiveCheckbox.isSelected()) flags = flags | Pattern.CASE_INSENSITIVE;
            if (this.jDotallCheckbox.isSelected()) flags = flags | Pattern.DOTALL;
            if (this.jLiteralCheckbox.isSelected()) flags = flags | Pattern.LITERAL;
            if (this.jCharacterClassesCheckbox.isSelected())
                flags = flags | Pattern.UNICODE_CHARACTER_CLASS;
            pattern = Pattern.compile(this.jRegexField.getText(), flags);
        }
        catch (Exception e) {
            RegexTester.reportException(
                    new Exception("Could not compile regular expression: " + e.getMessage()));
            return;
        }
        
        String text = this.jTestTextArea.getText();
        Matcher matcher = pattern.matcher(text);
        int matchCount = 0;
        DefaultTableModel model = new DefaultTableModel();
        while (matcher.find()) {
            matchCount ++;
            Vector matchValues = new Vector();
            for (int i = 0 ; i <= matcher.groupCount(); i++) {
                String match = matcher.group(i);
                matchValues.add(match);
            }
            model.addColumn("Match " + Integer.toString(matchCount), matchValues);
        }
        this.jResultsTable.setModel(model);
        this.jDoesMatchLabel.setText(Integer.toString(matchCount));
    }//GEN-LAST:event_jTestButtonActionPerformed

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        this.application.getProps().setProperty("regex", this.jRegexField.getText());
        this.application.getProps().setProperty("text", this.jTestTextArea.getText());
        this.application.shutdown();
    }//GEN-LAST:event_onWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCaseInsensitiveCheckbox;
    private javax.swing.JCheckBox jCharacterClassesCheckbox;
    private javax.swing.JLabel jDoesMatchLabel;
    private javax.swing.JCheckBox jDotallCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox jLiteralCheckbox;
    private javax.swing.JCheckBox jMultilineCheckbox;
    private javax.swing.JTextField jRegexField;
    private javax.swing.JTable jResultsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jTestButton;
    private javax.swing.JTextArea jTestTextArea;
    // End of variables declaration//GEN-END:variables
}
