/**
 * Part of the AddressDiscoverer project, licensed under the GPL v.3 license.
 * This project provides intelligence for discovering email addresses in
 * specified web pages, associating them with a given institution and department
 * and address type.
 *
 * This project is licensed under the GPL v.3. Your rights to copy and modify
 * are regulated by the conditions specified in that license, available at
 * http://www.gnu.org/licenses/gpl-3.0.html
 */
package org.norvelle.addressdiscoverer.gui;

/**
 *
 * @author Erik Norvelle <erik.norvelle@cyberlogos.co>
 */
public class AddModifyDeleteButtonPanel extends javax.swing.JPanel {

    private IListPanel parent;
    
    /**
     * Creates new form AddModifyDeleteButtonPanel
     */
    public AddModifyDeleteButtonPanel() {
        initComponents();
    }
    
    public void setParent(IListPanel parent) {
        this.parent = parent;
    }
    
    public void setNoObjectSelectedCondition() {
        this.jChangeButton.setEnabled(false);
        this.jDeleteButton.setEnabled(false);
        this.jNewButton.setEnabled(true);
    }
    
    public void setObjectSelectedCondition() {
        this.jChangeButton.setEnabled(true);
        this.jDeleteButton.setEnabled(true);
        this.jNewButton.setEnabled(true);
    }
    
    public void setDisabledCondition() {
        this.jChangeButton.setEnabled(false);
        this.jDeleteButton.setEnabled(false);
        this.jNewButton.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNewButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jChangeButton = new javax.swing.JButton();

        jNewButton.setText("New");
        jNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewButtonActionPerformed(evt);
            }
        });

        jDeleteButton.setText("Delete");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jChangeButton.setText("Change");
        jChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jChangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jNewButton)
                .addComponent(jDeleteButton)
                .addComponent(jChangeButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewButtonActionPerformed
        this.parent.addNew();
    }//GEN-LAST:event_jNewButtonActionPerformed

    private void jChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeButtonActionPerformed
        this.parent.modifySelected();
    }//GEN-LAST:event_jChangeButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        this.parent.deleteSelected();
    }//GEN-LAST:event_jDeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChangeButton;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jNewButton;
    // End of variables declaration//GEN-END:variables
}
