/**
 * Part of the AddressDiscoverer project, licensed under the GPL v.3 license.
 * This project provides intelligence for discovering email addresses in
 * specified web pages, associating them with a given institution and department
 * and address type.
 *
 * This project is licensed under the GPL v.3. Your rights to copy and modify
 * are regulated by the conditions specified in that license, available at
 * http://www.gnu.org/licenses/gpl-3.0.html
 */
package org.norvelle.addressdiscoverer.gui;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.norvelle.addressdiscoverer.AddressDiscoverer;
import org.norvelle.addressdiscoverer.model.Individual;
import org.norvelle.addressdiscoverer.model.KnownFirstName;
import org.norvelle.addressdiscoverer.model.KnownLastName;

/**
 *
 * @author Erik Norvelle <erik.norvelle@cyberlogos.co>
 */
public class EditIndividualDialog extends javax.swing.JDialog {

    Individual individual;
    EmailDiscoveryPanel parent;
    
    /**
     * Creates new form EditIndividualDialog
     * @param parent
     * @param individual
     * @param modal
     */
    public EditIndividualDialog(EmailDiscoveryPanel parent, Individual individual, boolean modal) {
        super((JFrame)null, modal);
        this.individual = individual;
        this.parent = parent;
        initComponents();
        this.jTitleField.setText(individual.getTitle());
        this.jFirstNameField.setText(individual.getFirstName());
        this.jLastNameField.setText(individual.getLastName());
        this.jEmailName.setText(individual.getEmail());
        this.jRestName.setText(individual.getUnprocessed());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFirstNameField = new javax.swing.JTextField();
        jLastNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jEmailName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTitleField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRestName = new javax.swing.JTextField();
        jCancelButton = new javax.swing.JButton();
        jOkButton = new javax.swing.JButton();
        jDeleteFirstNameButton = new javax.swing.JButton();
        jAddFirstNameButton = new javax.swing.JButton();
        jDeleteLastNameButton = new javax.swing.JButton();
        jAddLastNameButton = new javax.swing.JButton();
        jDeleteIndividualButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Individual");

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Email:");

        jLabel4.setText("Title:");

        jTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTitleFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Rest:");

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jOkButton.setText("Ok");
        jOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkButtonActionPerformed(evt);
            }
        });

        jDeleteFirstNameButton.setText("-");
        jDeleteFirstNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteFirstNameButtonActionPerformed(evt);
            }
        });

        jAddFirstNameButton.setText("+");
        jAddFirstNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddFirstNameButtonActionPerformed(evt);
            }
        });

        jDeleteLastNameButton.setText("-");
        jDeleteLastNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteLastNameButtonActionPerformed(evt);
            }
        });

        jAddLastNameButton.setText("+");
        jAddLastNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddLastNameButtonActionPerformed(evt);
            }
        });

        jDeleteIndividualButton.setText("Delete");
        jDeleteIndividualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteIndividualButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTitleField)
                            .addComponent(jEmailName)
                            .addComponent(jRestName)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLastNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFirstNameField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jAddLastNameButton)
                                    .addComponent(jAddFirstNameButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDeleteFirstNameButton)
                                    .addComponent(jDeleteLastNameButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jDeleteIndividualButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                        .addComponent(jOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDeleteFirstNameButton)
                    .addComponent(jAddFirstNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDeleteLastNameButton)
                    .addComponent(jAddLastNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelButton)
                    .addComponent(jOkButton)
                    .addComponent(jDeleteIndividualButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTitleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTitleFieldActionPerformed

    private void jOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkButtonActionPerformed
        if (!this.jTitleField.getText().equals(this.individual.getTitle()))
            this.individual.setTitle(this.jTitleField.getText());
        if (!this.jFirstNameField.getText().equals(this.individual.getFirstName()))
            this.individual.setFirstName(this.jFirstNameField.getText());
        if (!this.jLastNameField.getText().equals(this.individual.getLastName()))
            this.individual.setLastName(this.jLastNameField.getText());
        if (!this.jRestName.getText().equals(this.individual.getUnprocessed()))
            this.individual.setUnprocessed(this.jRestName.getText());
        if (!this.jEmailName.getText().equals(this.individual.getEmail()))
            this.individual.setUnprocessed(this.jRestName.getText());
        try {
            Individual.update(individual);
        } catch (SQLException ex) {
            AddressDiscoverer.reportException(ex);
        }
        this.parent.refreshResultsTable();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jOkButtonActionPerformed

    private void jAddLastNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddLastNameButtonActionPerformed
        String name = JOptionPane.showInputDialog("Add: ");
        KnownLastName.add(name);
    }//GEN-LAST:event_jAddLastNameButtonActionPerformed

    private void jDeleteLastNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteLastNameButtonActionPerformed
        String name = JOptionPane.showInputDialog("Delete: ");
        if (KnownLastName.isLastName(name))
            KnownLastName.delete(name);
    }//GEN-LAST:event_jDeleteLastNameButtonActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jDeleteIndividualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteIndividualButtonActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure?", "Confirm delete", 
                JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.NO_OPTION) 
            return;
        try {
            this.parent.notifyIndividualDeleted(individual);
            Individual.delete(this.individual);
        } catch (SQLException ex) {
            AddressDiscoverer.reportException(ex);
        }
        this.parent.refreshResultsTable();
        this.setVisible(false);
        this.dispose();        
    }//GEN-LAST:event_jDeleteIndividualButtonActionPerformed

    private void jAddFirstNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddFirstNameButtonActionPerformed
        String name = JOptionPane.showInputDialog("Add: ");
        KnownFirstName.add(name);
    }//GEN-LAST:event_jAddFirstNameButtonActionPerformed

    private void jDeleteFirstNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteFirstNameButtonActionPerformed
        String name = JOptionPane.showInputDialog("Delete: ");
        if (KnownFirstName.isFirstName(name))
            KnownFirstName.delete(name);
    }//GEN-LAST:event_jDeleteFirstNameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddFirstNameButton;
    private javax.swing.JButton jAddLastNameButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jDeleteFirstNameButton;
    private javax.swing.JButton jDeleteIndividualButton;
    private javax.swing.JButton jDeleteLastNameButton;
    private javax.swing.JTextField jEmailName;
    private javax.swing.JTextField jFirstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jLastNameField;
    private javax.swing.JButton jOkButton;
    private javax.swing.JTextField jRestName;
    private javax.swing.JTextField jTitleField;
    // End of variables declaration//GEN-END:variables
}
