/**
 * Part of the AddressDiscoverer project, licensed under the GPL v.3 license.
 * This project provides intelligence for discovering email addresses in
 * specified web pages, associating them with a given institution and department
 * and address type.
 *
 * This project is licensed under the GPL v.3. Your rights to copy and modify
 * are regulated by the conditions specified in that license, available at
 * http://www.gnu.org/licenses/gpl-3.0.html
 */
package org.norvelle.addressdiscoverer.gui;

/**
 *
 * @author Erik Norvelle <erik.norvelle@cyberlogos.co>
 */
public class EmailDiscoveryPanel extends javax.swing.JPanel {

    private ThreeWaySplitPane parent;
    
    /**
     * Creates new form EmailDiscoveryPanel
     */
    public EmailDiscoveryPanel(ThreeWaySplitPane parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEmailsDiscoveryTabbedPane = new javax.swing.JTabbedPane();
        jEmailSourcePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jWebAddressField = new javax.swing.JTextField();
        jRetrieveHTMLButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBytesReceivedLabel = new javax.swing.JLabel();
        jEmailDisplayPanel = new javax.swing.JPanel();

        jLabel1.setText("Web address:");

        jRetrieveHTMLButton.setText("Retrieve HTML");

        jLabel2.setText("Bytes received:");

        jBytesReceivedLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBytesReceivedLabel.setText("0");

        javax.swing.GroupLayout jEmailSourcePanelLayout = new javax.swing.GroupLayout(jEmailSourcePanel);
        jEmailSourcePanel.setLayout(jEmailSourcePanelLayout);
        jEmailSourcePanelLayout.setHorizontalGroup(
            jEmailSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEmailSourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEmailSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEmailSourcePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWebAddressField))
                    .addGroup(jEmailSourcePanelLayout.createSequentialGroup()
                        .addComponent(jRetrieveHTMLButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBytesReceivedLabel)
                        .addGap(0, 308, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jEmailSourcePanelLayout.setVerticalGroup(
            jEmailSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEmailSourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEmailSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jWebAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jEmailSourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRetrieveHTMLButton)
                    .addComponent(jLabel2)
                    .addComponent(jBytesReceivedLabel))
                .addContainerGap(439, Short.MAX_VALUE))
        );

        jEmailsDiscoveryTabbedPane.addTab("Source Page", jEmailSourcePanel);

        javax.swing.GroupLayout jEmailDisplayPanelLayout = new javax.swing.GroupLayout(jEmailDisplayPanel);
        jEmailDisplayPanel.setLayout(jEmailDisplayPanelLayout);
        jEmailDisplayPanelLayout.setHorizontalGroup(
            jEmailDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        jEmailDisplayPanelLayout.setVerticalGroup(
            jEmailDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jEmailsDiscoveryTabbedPane.addTab("Discovered Emails", jEmailDisplayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEmailsDiscoveryTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEmailsDiscoveryTabbedPane)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBytesReceivedLabel;
    private javax.swing.JPanel jEmailDisplayPanel;
    private javax.swing.JPanel jEmailSourcePanel;
    private javax.swing.JTabbedPane jEmailsDiscoveryTabbedPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jRetrieveHTMLButton;
    private javax.swing.JTextField jWebAddressField;
    // End of variables declaration//GEN-END:variables
}
